eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8762
spring:
  application:
    name: service-hi
  datasource:
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/spc?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver



mybatis:
  mapper-locations: classpath*:com/spc/server/mapper/*Mapper.xml
  type-aliases-package: com.spc.server.pojo

#showSql
logging:
  level:
    com.spc.server.dao: trace



